id: ch.fhir.ig.ch-emr
canonical: http://fhir.ch/ig/ch-emr
name: CH_EMR
title: "CH EMR (R4)"
description: FHIR Implementation Guide for the Swiss Electronic Emergency Record
status: active
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2026-06-12
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: HL7 Switzerland
contact:
  - name: HL7 Switzerland
    telecom:
      - system: url
        value: https://www.hl7.ch/

dependencies:
  hl7.terminology.r4: 
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    version: 7.1.0
  ch.fhir.ig.ch-core:
    uri: http://fhir.ch/ig/ch-core/ImplementationGuide/ch.fhir.ig.ch-core
    version: 7.0.0-ballot
  ch.fhir.ig.ch-term:
    uri: http://fhir.ch/ig/ch-term/ImplementationGuide/ch.fhir.ig.ch-term
    version: 3.4.x
  ch.fhir.ig.ch-ips:
    uri: http://fhir.ch/ig/ch-ips/ImplementationGuide/ch.fhir.ig.ch-ips
    version: 2.0.0
  ch.fhir.ig.ch-emed:
    uri: http://fhir.ch/ig/ch-emed/ImplementationGuide/ch.fhir.ig.ch-emed
    version: 6.0.0
  hl7.fhir.uv.extensions.r4:
    uri: http://hl7.org/fhir/extensions/ImplementationGuide/hl7.fhir.uv.extensions
    version: 5.2.0
  hl7.fhir.uv.ips:
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    version: 2.0.0

pages:
  index.md:
    title: Home
  document.md:
    title: Document
  usecase-german.md:
    title: Anwendungsfälle
  usecase-french.md:
    title: Cas d'application
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  security.md:
    title: Security and Privacy
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Document: document.html
  Use Case:
   German: usecase-german.html
   French: usecase-french.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Security: security.html
  Artifacts: artifacts.html

parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true 
  path-expansion-params: '../../expansion-params.json'  # for using SNOMED CT Swiss Extension
  pin-canonicals: pin-multiples
  path-resource:
    - input/resources  

FSHOnly: false
applyExtensionMetadataToRoot: false
instanceOptions:
  setMetaProfile: always
  setId: always
  manualSliceOrdering: true
